WellCommerce\Bundle\CurrencyBundle\Entity\Currency:
    fields:
        id:
            groups:
                - default
                - currency
        code:
            groups:
                - default
                - currency
        createdAt:
            groups:
                - default
                - currency
        updatedAt:
            groups:
                - default
                - currency
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations: {  }
    callbacks: {  }
