well_commerce_availability:
    services:
        availability:
            auto_services:
                factory: WellCommerce\Bundle\AvailabilityBundle\Factory\AvailabilityFactory
                repository: WellCommerce\Bundle\AvailabilityBundle\Repository\AvailabilityRepository
            orm_configuration:
                mapping: "@WellCommerceAvailabilityBundle/Resources/config/doctrine/Availability.orm.yml"
                entity: WellCommerce\Bundle\AvailabilityBundle\Entity\Availability
            api_configuration:
                exposed: true
                dataset: availability.dataset.admin
                manager: availability.manager.admin
        availability_translation:
            orm_configuration:
                mapping: "@WellCommerceAvailabilityBundle/Resources/config/doctrine/AvailabilityTranslation.orm.yml"
                entity: WellCommerce\Bundle\AvailabilityBundle\Entity\AvailabilityTranslation


