WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodTranslation:
    fields:
        name:
            groups:
                - default
                - shipping_method_translation
        locale:
            groups:
                - default
                - shipping_method_translation
        id:
            groups:
                - default
                - shipping_method_translation
    associations:
        translatable:
            groups:
                - shipping_method_translation
    callbacks: {  }
