WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethod:
    fields:
        id:
            groups:
                - default
                - shipping_method
        calculator:
            groups:
                - default
                - shipping_method
        enabled:
            groups:
                - default
                - shipping_method
        hierarchy:
            groups:
                - default
                - shipping_method
        createdAt:
            groups:
                - default
                - shipping_method
        updatedAt:
            groups:
                - default
                - shipping_method
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        costs:
            groups:
                - shipping_method
        currency:
            groups:
                - shipping_method
        tax:
            groups:
                - shipping_method
        paymentMethods:
            groups:
                - shipping_method
        translations:
            groups:
                - shipping_method
    callbacks: {  }
