WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodCost:
    fields:
        id:
            groups:
                - default
                - shipping_method_cost
        rangeFrom:
            groups:
                - default
                - shipping_method_cost
        rangeTo:
            groups:
                - default
                - shipping_method_cost
        cost:
            groups:
                - default
                - shipping_method_cost
        createdAt:
            groups:
                - default
                - shipping_method_cost
        updatedAt:
            groups:
                - default
                - shipping_method_cost
    associations:
        shippingMethod:
            groups:
                - shipping_method_cost
    callbacks: {  }
