WellCommerce\Bundle\AttributeBundle\Entity\AttributeValueTranslation:
    type: entity
    table: attribute_value_translation
    fields:
        name:
            type: string
            length: 255
            nullable: false
