WellCommerce\Bundle\UnitBundle\Entity\UnitTranslation:
    fields:
        name:
            groups:
                - default
                - unit_translation
        locale:
            groups:
                - default
                - unit_translation
        id:
            groups:
                - default
                - unit_translation
    associations:
        translatable:
            groups:
                - unit_translation
    callbacks: {  }
