WellCommerce\Bundle\UnitBundle\Entity\Unit:
    fields:
        id:
            groups:
                - default
                - unit
        createdAt:
            groups:
                - default
                - unit
        updatedAt:
            groups:
                - default
                - unit
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        translations:
            groups:
                - unit
    callbacks: {  }
