well_commerce_payment:
    services:
        payment:
            auto_services:
                factory: WellCommerce\Bundle\PaymentBundle\Factory\PaymentFactory
                repository: WellCommerce\Bundle\PaymentBundle\Repository\PaymentRepository
            orm_configuration:
                mapping: "@WellCommercePaymentBundle/Resources/config/doctrine/Payment.orm.yml"
                entity: WellCommerce\Bundle\PaymentBundle\Entity\Payment
        payment_method:
            auto_services:
                factory: WellCommerce\Bundle\PaymentBundle\Factory\PaymentMethodFactory
                repository: WellCommerce\Bundle\PaymentBundle\Repository\PaymentMethodRepository
            orm_configuration:
                mapping: "@WellCommercePaymentBundle/Resources/config/doctrine/PaymentMethod.orm.yml"
                entity: WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethod
            api_configuration:
                exposed: true
                dataset: payment_method.dataset.admin
                manager: payment_method.manager.admin
        payment_method_configuration:
            auto_services:
                factory: WellCommerce\Bundle\PaymentBundle\Factory\PaymentMethodConfigurationFactory
                repository: WellCommerce\Bundle\PaymentBundle\Repository\PaymentMethodConfigurationRepository
            orm_configuration:
                mapping: "@WellCommercePaymentBundle/Resources/config/doctrine/PaymentMethodConfiguration.orm.yml"
                entity: WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethodConfiguration
        payment_method_translation:
            orm_configuration:
                mapping: "@WellCommercePaymentBundle/Resources/config/doctrine/PaymentMethodTranslation.orm.yml"
                entity: WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethodTranslation
