tools:
    php_cpd: true
    php_sim: false
    php_pdepend: true
    php_analyzer: true

filter:
    excluded_paths:
        - tests/*
        - app/*
        - vendor/*
        - web/*
        - bin/*
        - src/*Bundle/DataFixtures/
        - src/*Bundle/Tests/
