language: php

sudo: false

matrix:
    include:
        - php: 5.6
        - php: 7.0

addons:
    apt:
        packages:
            - apache2

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - echo "zend.enable_gc = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

    - mysql -e 'CREATE DATABASE travis;'
    - cp app/config/parameters.yml.travis app/config/parameters.yml

    - composer self-update
    - composer install --no-interaction

    - php app/console wellcommerce:install
    - php app/console cache:warmup --env=test

script:
    - bin/phpunit -c app/phpunit.xml.dist

notifications:
    email: false
    slack: wellcommerce:5g1PqYtrlI40NVxaiuFzeG9z
