WellCommerce\Bundle\CartBundle\Entity\Cart:
    type: entity
    table: cart
    repositoryClass: WellCommerce\Bundle\CartBundle\Repository\CartRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    embedded:
        totals:
            class: WellCommerce\Bundle\CartBundle\Entity\CartTotals
            columnPrefix: total_
        billingAddress:
            class: WellCommerce\Bundle\ClientBundle\Entity\ClientBillingAddress
            columnPrefix: billing_address_
        shippingAddress:
            class: WellCommerce\Bundle\ClientBundle\Entity\ClientShippingAddress
            columnPrefix: shipping_address_
        contactDetails:
            class: WellCommerce\Bundle\ClientBundle\Entity\ClientContactDetails
            columnPrefix: contact_details_
    fields:
        sessionId:
            type: string
            unique: true
            nullable: false
            column: session_id
        currency:
            type: string
            length: 16
            nullable: false
            column: currency
        copyAddress:
            type: integer
            nullable: false
            column: copy_address
            options:
                default: 1
    oneToMany:
        products:
            targetEntity: WellCommerce\Bundle\CartBundle\Entity\CartProductInterface
            cascade:
                - all
            fetch: LAZY
            mappedBy: cart
            orphanRemoval: true
    manyToOne:
        coupon:
            targetEntity: WellCommerce\Bundle\CouponBundle\Entity\Coupon
            fetch: LAZY
            joinColumns:
                coupon_id:
                    referencedColumnName: id
                    onDelete: SET NULL
        shop:
            targetEntity: WellCommerce\Bundle\ShopBundle\Entity\ShopInterface
            fetch: LAZY
            joinColumns:
                shop_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        shippingMethodCost:
            targetEntity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodCost
            fetch: LAZY
            joinColumns:
                shipping_method_cost_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        paymentMethod:
            targetEntity: WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethod
            fetch: LAZY
            joinColumns:
                payment_method_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
    oneToOne:
        client:
            targetEntity: WellCommerce\Bundle\ClientBundle\Entity\Client
            fetch: LAZY
            nullable: true
            joinColumns:
                client_id:
                    referencedColumnName: id
                    onDelete: CASCADE
