WellCommerce\Bundle\LocaleBundle\Entity\Locale:
    fields:
        id:
            groups:
                - default
                - locale
        code:
            groups:
                - default
                - locale
        createdAt:
            groups:
                - default
                - locale
        updatedAt:
            groups:
                - default
                - locale
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        currency:
            groups:
                - locale
    callbacks: {  }
