WellCommerce\Bundle\OrderBundle\Entity\OrderStatusGroup:
    fields:
        id:
            groups:
                - default
                - order_status_group
        createdAt:
            groups:
                - default
                - order_status_group
        updatedAt:
            groups:
                - default
                - order_status_group
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        translations:
            groups:
                - order_status_group
    callbacks: {  }
