WellCommerce\Bundle\OrderBundle\Entity\OrderStatusGroupTranslation:
    fields:
        name:
            groups:
                - default
                - order_status_group_translation
        locale:
            groups:
                - default
                - order_status_group_translation
        id:
            groups:
                - default
                - order_status_group_translation
    associations:
        translatable:
            groups:
                - order_status_group_translation
    callbacks: {  }
