WellCommerce\Bundle\OrderBundle\Entity\OrderTotalDetail:
    fields:
        id:
            groups:
                - default
                - order_total_detail
        collector:
            groups:
                - default
                - order_total_detail
        modifierType:
            groups:
                - default
                - order_total_detail
        modifierValue:
            groups:
                - default
                - order_total_detail
        subtraction:
            groups:
                - default
                - order_total_detail
        hierarchy:
            groups:
                - default
                - order_total_detail
        orderTotal:
            groups:
                - default
                - order_total_detail
    associations:
        order:
            groups:
                - order_total_detail
    callbacks: {  }
