WellCommerce\Bundle\OrderBundle\Entity\OrderTotal:
    fields:
        netAmount:
            groups:
                - default
                - order_total
        grossAmount:
            groups:
                - default
                - order_total
        taxAmount:
            groups:
                - default
                - order_total
        taxRate:
            groups:
                - default
                - order_total
        currency:
            groups:
                - default
                - order_total
    associations: {  }
    callbacks: {  }
