WellCommerce\Bundle\OrderBundle\Entity\Order:
    fields:
        id:
            groups:
                - default
                - order
        sessionId:
            groups:
                - default
                - order
        currency:
            groups:
                - default
                - order
        comment:
            groups:
                - default
                - order
        billingAddress:
            groups:
                - default
                - order
        shippingAddress:
            groups:
                - default
                - order
        contactDetails:
            groups:
                - default
                - order
        orderTotal:
            groups:
                - default
                - order
        productTotal:
            groups:
                - default
                - order
        shippingTotal:
            groups:
                - default
                - order
        createdAt:
            groups:
                - default
                - order
        updatedAt:
            groups:
                - default
                - order
    associations:
        products:
            groups:
                - order
        totals:
            groups:
                - order
        payments:
            groups:
                - order
        coupon:
            groups:
                - order
        client:
            groups:
                - order
        paymentMethod:
            groups:
                - order
        currentStatus:
            groups:
                - order
        shippingMethod:
            groups:
                - order
        shop:
            groups:
                - order
    callbacks: {  }
