WellCommerce\Bundle\ProducerBundle\Entity\ProducerTranslation:
    fields:
        name:
            groups:
                - default
                - producer_translation
        shortDescription:
            groups:
                - default
                - producer_translation
        description:
            groups:
                - default
                - producer_translation
        slug:
            groups:
                - default
                - producer_translation
        meta:
            groups:
                - default
                - producer_translation
        locale:
            groups:
                - default
                - producer_translation
        id:
            groups:
                - default
                - producer_translation
    associations:
        route:
            groups:
                - producer_translation
        translatable:
            groups:
                - producer_translation
    callbacks: {  }
