WellCommerce\Bundle\ProducerBundle\Entity\Producer:
    fields:
        id:
            groups:
                - default
                - producer
        createdAt:
            groups:
                - default
                - producer
        updatedAt:
            groups:
                - default
                - producer
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        products:
            groups:
                - producer
        photo:
            groups:
                - producer
        deliverers:
            groups:
                - producer
        shops:
            groups:
                - producer
        translations:
            groups:
                - producer
    callbacks: {  }
