WellCommerce\Bundle\ProducerBundle\Entity\ProducerRoute:
    fields:
        id:
            groups:
                - default
                - producer_route
        path:
            groups:
                - default
                - producer_route
        locale:
            groups:
                - default
                - producer_route
    associations:
        identifier:
            groups:
                - producer_route
    callbacks: {  }
