WellCommerce\Bundle\CategoryBundle\Entity\Category:
    fields:
        id:
            groups:
                - default
                - category
        hierarchy:
            groups:
                - default
                - category
        enabled:
            groups:
                - default
                - category
        createdAt:
            groups:
                - default
                - category
        updatedAt:
            groups:
                - default
                - category
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        children:
            groups:
                - category
        parent:
            groups:
                - category
        products:
            groups:
                - category
        shops:
            groups:
                - category
        translations:
            groups:
                - category
    callbacks: {  }
