WellCommerce\Bundle\CategoryBundle\Entity\CategoryTranslation:
    fields:
        name:
            groups:
                - default
                - category_translation
        shortDescription:
            groups:
                - default
                - category_translation
        description:
            groups:
                - default
                - category_translation
        slug:
            groups:
                - default
                - category_translation
        meta:
            groups:
                - default
                - category_translation
        locale:
            groups:
                - default
                - category_translation
        id:
            groups:
                - default
                - category_translation
    associations:
        route:
            groups:
                - category_translation
        translatable:
            groups:
                - category_translation
    callbacks: {  }
