WellCommerce\Bundle\CategoryBundle\Entity\CategoryRoute:
    fields:
        id:
            groups:
                - default
                - category_route
        path:
            groups:
                - default
                - category_route
        locale:
            groups:
                - default
                - category_route
    associations:
        identifier:
            groups:
                - category_route
    callbacks: {  }
