WellCommerce\Bundle\ShopBundle\Entity\Shop:
    fields:
        id:
            groups:
                - default
                - shop
        name:
            groups:
                - default
                - shop
        url:
            groups:
                - default
                - shop
        defaultCountry:
            groups:
                - default
                - shop
        defaultCurrency:
            groups:
                - default
                - shop
        mailerConfiguration:
            groups:
                - default
                - shop
        createdAt:
            groups:
                - default
                - shop
        updatedAt:
            groups:
                - default
                - shop
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        company:
            groups:
                - shop
        theme:
            groups:
                - shop
    callbacks: {  }
