WellCommerce\Bundle\ThemeBundle\Entity\Theme:
    fields:
        id:
            groups:
                - default
                - theme
        name:
            groups:
                - default
                - theme
        folder:
            groups:
                - default
                - theme
        createdAt:
            groups:
                - default
                - theme
        updatedAt:
            groups:
                - default
                - theme
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        css:
            groups:
                - theme
    callbacks: {  }
