WellCommerce\Bundle\ThemeBundle\Entity\ThemeCss:
    fields:
        id:
            groups:
                - default
                - theme_css
        class:
            groups:
                - default
                - theme_css
        selector:
            groups:
                - default
                - theme_css
        attribute:
            groups:
                - default
                - theme_css
        createdAt:
            groups:
                - default
                - theme_css
        updatedAt:
            groups:
                - default
                - theme_css
    associations:
        theme:
            groups:
                - theme_css
    callbacks: {  }
