WellCommerce\Bundle\ClientBundle\Entity\ClientDetails:
    fields:
        discount:
            groups:
                - default
                - client_details
        password:
            groups: {  }
        username:
            groups:
                - default
                - client_details
        salt:
            groups: {  }
        resetPasswordHash:
            groups:
                - default
                - client_details
        conditionsAccepted:
            groups:
                - default
                - client_details
        newsletterAccepted:
            groups:
                - default
                - client_details
    associations: {  }
    callbacks: {  }
