WellCommerce\Bundle\ClientBundle\Entity\Client:
    fields:
        id:
            groups:
                - default
                - client
        clientDetails:
            groups:
                - default
                - client
        billingAddress:
            groups:
                - default
                - client
        shippingAddress:
            groups:
                - default
                - client
        contactDetails:
            groups:
                - default
                - client
        createdAt:
            groups:
                - default
                - client
        updatedAt:
            groups:
                - default
                - client
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        wishlist:
            groups:
                - client
        orders:
            groups:
                - client
        clientGroup:
            groups:
                - client
        shop:
            groups:
                - client
    callbacks: {  }
