WellCommerce\Bundle\ClientBundle\Entity\ClientGroupTranslation:
    fields:
        name:
            groups:
                - default
                - client_group_translation
        locale:
            groups:
                - default
                - client_group_translation
        id:
            groups:
                - default
                - client_group_translation
    associations:
        translatable:
            groups:
                - client_group_translation
    callbacks: {  }
