WellCommerce\Bundle\ClientBundle\Entity\ClientContactDetails:
    fields:
        firstName:
            groups:
                - default
                - client_contact_details
        lastName:
            groups:
                - default
                - client_contact_details
        phone:
            groups:
                - default
                - client_contact_details
        secondaryPhone:
            groups:
                - default
                - client_contact_details
        email:
            groups:
                - default
                - client_contact_details
    associations: {  }
    callbacks: {  }
