WellCommerce\Bundle\ClientBundle\Entity\ClientGroup:
    fields:
        id:
            groups:
                - default
                - client_group
        discount:
            groups:
                - default
                - client_group
        createdAt:
            groups:
                - default
                - client_group
        updatedAt:
            groups:
                - default
                - client_group
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        clients:
            groups:
                - client_group
        pages:
            groups:
                - client_group
        translations:
            groups:
                - client_group
    callbacks: {  }
