WellCommerce\Bundle\TaxBundle\Entity\TaxTranslation:
    type: entity
    table: tax_translation
    fields:
        name:
            type: string
            length: 255
            nullable: false
