well_commerce_dictionary:
    services:
        dictionary:
            auto_services:
                factory: WellCommerce\Bundle\DictionaryBundle\Factory\DictionaryFactory
                repository: WellCommerce\Bundle\DictionaryBundle\Repository\DictionaryRepository
            orm_configuration:
                mapping: "@WellCommerceDictionaryBundle/Resources/config/doctrine/Dictionary.orm.yml"
                entity: WellCommerce\Bundle\DictionaryBundle\Entity\Dictionary
        dictionary_translation:
            orm_configuration:
                mapping: "@WellCommerceDictionaryBundle/Resources/config/doctrine/DictionaryTranslation.orm.yml"
                entity: WellCommerce\Bundle\DictionaryBundle\Entity\DictionaryTranslation
