WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodTranslation:
    type: entity
    table: shipping_method_translation
    fields:
        name:
            type: string
            length: 255
            nullable: false
