WellCommerce\Bundle\CartBundle\Entity\CartTotals:
    fields:
        quantity:
            groups:
                - default
                - cart_totals
        weight:
            groups:
                - default
                - cart_totals
        netPrice:
            groups:
                - default
                - cart_totals
        grossPrice:
            groups:
                - default
                - cart_totals
        taxAmount:
            groups:
                - default
                - cart_totals
    associations: {  }
    callbacks: {  }
