WellCommerce\Bundle\CartBundle\Entity\CartProduct:
    fields:
        id:
            groups:
                - default
                - cart_product
        quantity:
            groups:
                - default
                - cart_product
        createdAt:
            groups:
                - default
                - cart_product
        updatedAt:
            groups:
                - default
                - cart_product
    associations:
        cart:
            groups:
                - cart_product
        product:
            groups:
                - cart_product
        attribute:
            groups:
                - cart_product
    callbacks: {  }
