WellCommerce\Bundle\CartBundle\Entity\Cart:
    fields:
        id:
            groups:
                - default
                - cart
        sessionId:
            groups:
                - default
                - cart
        currency:
            groups:
                - default
                - cart
        copyAddress:
            groups:
                - default
                - cart
        totals:
            groups:
                - default
                - cart
        billingAddress:
            groups:
                - default
                - cart
        shippingAddress:
            groups:
                - default
                - cart
        contactDetails:
            groups:
                - default
                - cart
        createdAt:
            groups:
                - default
                - cart
        updatedAt:
            groups:
                - default
                - cart
    associations:
        client:
            groups:
                - cart
        coupon:
            groups:
                - cart
        shippingMethodCost:
            groups:
                - cart
        paymentMethod:
            groups:
                - cart
        products:
            groups:
                - cart
        shop:
            groups:
                - cart
    callbacks: {  }
