well_commerce_wishlist:
    services:
        wishlist:
            auto_services:
                factory: WellCommerce\Bundle\WishlistBundle\Factory\WishlistFactory
                repository: WellCommerce\Bundle\WishlistBundle\Repository\WishlistRepository
            orm_configuration:
                mapping: "@WellCommerceWishlistBundle/Resources/config/doctrine/Wishlist.orm.yml"
                entity: WellCommerce\Bundle\WishlistBundle\Entity\Wishlist
