language: php

sudo: false

php:
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 7.0

addons:
    apt:
        packages:
            - apache2

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

    - composer self-update
    - composer install --prefer-source --no-interaction

script:
    - vendor/phpunit/phpunit/phpunit -c phpunit.xml.dist --testdox

notifications:
    email: false
    slack: wellcommerce:5g1PqYtrlI40NVxaiuFzeG9z
