WellCommerce\Bundle\AppBundle\Entity\DiscountablePrice:
    type: embeddable
    fields:
        discountedNetAmount:
            type: decimal
            scale: 2
            nullable: true
            precision: 15
            column: discounted_net_amount
        discountedGrossAmount:
            type: decimal
            scale: 2
            nullable: true
            precision: 15
            column: discounted_gross_amount
        discountedTaxAmount:
            type: decimal
            scale: 2
            nullable: true
            precision: 15
            column: discounted_tax_amount
        validFrom:
            type: datetime
            nullable: true
            column: valid_from
        validTo:
            type: datetime
            nullable: true
            column: valid_to
