WellCommerce\Bundle\AppBundle\Entity\MailerConfiguration:
    type: embeddable
    fields:
        from:
            type: string
            length: 64
            nullable: true
        host:
            type: string
            length: 64
            nullable: true
        port:
            type: integer
            nullable: true
        user:
            type: string
            length: 64
            nullable: true
        pass:
            type: string
            length: 64
            nullable: true
