well_commerce_shop:
    services:
        shop:
            auto_services:
                factory: WellCommerce\Bundle\ShopBundle\Factory\ShopFactory
                repository: WellCommerce\Bundle\ShopBundle\Repository\ShopRepository
            orm_configuration:
                mapping: "@WellCommerceShopBundle/Resources/config/doctrine/Shop.orm.yml"
                entity: WellCommerce\Bundle\ShopBundle\Entity\Shop
            api_configuration:
                exposed: true
                dataset: shop.dataset.admin
                manager: shop.manager.admin

doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\ShopBundle\Entity\ShopInterface: WellCommerce\Bundle\ShopBundle\Entity\Shop
