WellCommerce\Bundle\AttributeBundle\Entity\AttributeGroupTranslation:
    fields:
        name:
            groups:
                - default
                - attribute_group_translation
        locale:
            groups:
                - default
                - attribute_group_translation
        id:
            groups:
                - default
                - attribute_group_translation
    associations:
        translatable:
            groups:
                - attribute_group_translation
    callbacks: {  }
