WellCommerce\Bundle\AttributeBundle\Entity\AttributeGroup:
    fields:
        id:
            groups:
                - default
                - attribute_group
        createdAt:
            groups:
                - default
                - attribute_group
        updatedAt:
            groups:
                - default
                - attribute_group
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        attributes:
            groups:
                - attribute_group
        translations:
            groups:
                - attribute_group
    callbacks: {  }
