WellCommerce\Bundle\AttributeBundle\Entity\Attribute:
    fields:
        id:
            groups:
                - default
                - attribute
        createdAt:
            groups:
                - default
                - attribute
        updatedAt:
            groups:
                - default
                - attribute
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        values:
            groups:
                - attribute
        attributeGroup:
            groups:
                - attribute
        translations:
            groups:
                - attribute
    callbacks: {  }
