WellCommerce\Bundle\AttributeBundle\Entity\AttributeValueTranslation:
    fields:
        name:
            groups:
                - default
                - attribute_value_translation
        locale:
            groups:
                - default
                - attribute_value_translation
        id:
            groups:
                - default
                - attribute_value_translation
    associations:
        translatable:
            groups:
                - attribute_value_translation
    callbacks: {  }
