well_commerce_attribute:
    services:
        attribute:
            auto_services:
                factory: WellCommerce\Bundle\AttributeBundle\Factory\AttributeFactory
                repository: WellCommerce\Bundle\AttributeBundle\Repository\AttributeRepository
            orm_configuration:
                mapping: "@WellCommerceAttributeBundle/Resources/config/doctrine/Attribute.orm.yml"
                entity: WellCommerce\Bundle\AttributeBundle\Entity\Attribute
        attribute_translation:
            orm_configuration:
                mapping: "@WellCommerceAttributeBundle/Resources/config/doctrine/AttributeTranslation.orm.yml"
                entity: WellCommerce\Bundle\AttributeBundle\Entity\AttributeTranslation
        attribute_group:
            auto_services:
                factory: WellCommerce\Bundle\AttributeBundle\Factory\AttributeGroupFactory
                repository: WellCommerce\Bundle\AttributeBundle\Repository\AttributeGroupRepository
            orm_configuration:
                mapping: "@WellCommerceAttributeBundle/Resources/config/doctrine/AttributeGroup.orm.yml"
                entity: WellCommerce\Bundle\AttributeBundle\Entity\AttributeGroup
        attribute_group_translation:
            orm_configuration:
                mapping: "@WellCommerceAttributeBundle/Resources/config/doctrine/AttributeGroupTranslation.orm.yml"
                entity: WellCommerce\Bundle\AttributeBundle\Entity\AttributeGroupTranslation
        attribute_value:
            auto_services:
                factory: WellCommerce\Bundle\AttributeBundle\Factory\AttributeValueFactory
                repository: WellCommerce\Bundle\AttributeBundle\Repository\AttributeValueRepository
            orm_configuration:
                mapping: "@WellCommerceAttributeBundle/Resources/config/doctrine/AttributeValue.orm.yml"
                entity: WellCommerce\Bundle\AttributeBundle\Entity\AttributeValue
        attribute_value_translation:
            orm_configuration:
                mapping: "@WellCommerceAttributeBundle/Resources/config/doctrine/AttributeValueTranslation.orm.yml"
                entity: WellCommerce\Bundle\AttributeBundle\Entity\AttributeValueTranslation
