well_commerce_client:
    services:
        client:
            auto_services:
                factory: WellCommerce\Bundle\ClientBundle\Factory\ClientFactory
                repository: WellCommerce\Bundle\ClientBundle\Repository\ClientRepository
            orm_configuration:
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/Client.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\Client
            api_configuration:
                exposed: true
                dataset: client.dataset.admin
                manager: client.manager.admin
        client_billing_address:
            orm_configuration:
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientBillingAddress.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\ClientBillingAddress
        client_details:
            orm_configuration:
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientDetails.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\ClientDetails
        client_contact_details:
            orm_configuration:
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientContactDetails.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\ClientContactDetails
        client_group:
            auto_services:
                factory: WellCommerce\Bundle\ClientBundle\Factory\ClientGroupFactory
                repository: WellCommerce\Bundle\ClientBundle\Repository\ClientGroupRepository
            orm_configuration:
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientGroup.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\ClientGroup
            api_configuration:
                exposed: true
                dataset: client_group.dataset.admin
                manager: client_group.manager.admin
        client_group_translation:
            orm_configuration:
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientGroupTranslation.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\ClientGroupTranslation
        client_shipping_address:
            orm_configuration:
                mapping: "@WellCommerceClientBundle/Resources/config/doctrine/ClientShippingAddress.orm.yml"
                entity: WellCommerce\Bundle\ClientBundle\Entity\ClientShippingAddress
