WellCommerce\Bundle\ProductBundle\Entity\ProductPhoto:
    fields:
        id:
            groups:
                - default
                - product_photo
        mainPhoto:
            groups:
                - default
                - product_photo
        hierarchy:
            groups:
                - default
                - product_photo
        createdAt:
            groups:
                - default
                - product_photo
        updatedAt:
            groups:
                - default
                - product_photo
    associations:
        photo:
            groups:
                - product_photo
        product:
            groups:
                - product_photo
    callbacks: {  }
