WellCommerce\Bundle\ProductBundle\Entity\ProductAttribute:
    fields:
        id:
            groups:
                - default
                - product_attribute
        weight:
            groups:
                - default
                - product_attribute
        symbol:
            groups:
                - default
                - product_attribute
        stock:
            groups:
                - default
                - product_attribute
        modifierType:
            groups:
                - default
                - product_attribute
        modifierValue:
            groups:
                - default
                - product_attribute
        hierarchy:
            groups:
                - default
                - product_attribute
        sellPrice:
            groups:
                - default
                - product_attribute
        createdAt:
            groups:
                - default
                - product_attribute
        updatedAt:
            groups:
                - default
                - product_attribute
    associations:
        product:
            groups:
                - product_attribute
        availability:
            groups:
                - product_attribute
        photo:
            groups:
                - product_attribute
        attributeValues:
            groups:
                - product_attribute
    callbacks: {  }
