WellCommerce\Bundle\ProductBundle\Entity\ProductTranslation:
    fields:
        name:
            groups:
                - default
                - product_translation
        shortDescription:
            groups:
                - default
                - product_translation
        description:
            groups:
                - default
                - product_translation
        slug:
            groups:
                - default
                - product_translation
        meta:
            groups:
                - default
                - product_translation
        locale:
            groups:
                - default
                - product_translation
        id:
            groups:
                - default
                - product_translation
    associations:
        route:
            groups:
                - product_translation
        translatable:
            groups:
                - product_translation
    callbacks: {  }
