WellCommerce\Bundle\ClientBundle\Entity\ClientDetails:
    type: embeddable
    fields:
        discount:
            type: decimal
            scale: 2
            nullable: false
            precision: 15
        password:
            type: string
            length: 64
            nullable: false
        username:
            type: string
            length: 60
            unique: false
            nullable: false
        salt:
            type: string
            length: 40
            unique: false
            nullable: false
        resetPasswordHash:
            type: string
            length: 48
            unique: true
            nullable: true
        conditionsAccepted:
            type: boolean
            nullable: false
            column: conditions_accepted
        newsletterAccepted:
            type: boolean
            nullable: false
            column: newsletter_accepted
