well_commerce_category:
    services:
        category:
            auto_services:
                factory: WellCommerce\Bundle\CategoryBundle\Factory\CategoryFactory
                repository: WellCommerce\Bundle\CategoryBundle\Repository\CategoryRepository
            orm_configuration:
                mapping: "@WellCommerceCategoryBundle/Resources/config/doctrine/Category.orm.yml"
                entity: WellCommerce\Bundle\CategoryBundle\Entity\Category
            api_configuration:
                exposed: true
                dataset: category.dataset.admin
                manager: category.manager.admin
        category_route:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommerceCategoryBundle/Resources/config/doctrine/CategoryRoute.orm.yml"
                entity: WellCommerce\Bundle\CategoryBundle\Entity\CategoryRoute
        category_translation:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommerceCategoryBundle/Resources/config/doctrine/CategoryTranslation.orm.yml"
                entity: WellCommerce\Bundle\CategoryBundle\Entity\CategoryTranslation
    dynamic_routing:
        name: category
        entity: WellCommerce\Bundle\CategoryBundle\Entity\CategoryRoute
        generator: WellCommerce\Bundle\CategoryBundle\Routing\CategoryRouteGenerator
        defaults:
            _controller: category.controller.front:indexAction
            limit: 12
            page: 1
            orderBy: name
            orderDir: asc
            priceFrom: 0
            priceTo: 9999
            view: grid
            producers: ~
            attributes: ~
        requirements:
            limit: "\\d{1,10}"
            page: "\\d{1,10}"
            orderBy: "name|finalPrice"
            orderDir: "asc|desc"
            priceFrom: "\\d{1,10}"
            priceTo: "\\d{1,10}"
            view: "grid|list"
            producers: "[\\d+_]+"
            attributes: "[\\d+_]+"
        pattern: "{page},{limit},{orderBy},{orderDir},{priceFrom},{priceTo},{view},{producers},{attributes}"

