well_commerce_locale:
    services:
        locale:
            auto_services:
                factory: WellCommerce\Bundle\LocaleBundle\Factory\LocaleFactory
                repository: WellCommerce\Bundle\LocaleBundle\Repository\LocaleRepository
            orm_configuration:
                mapping: "@WellCommerceLocaleBundle/Resources/config/doctrine/Locale.orm.yml"
                entity: WellCommerce\Bundle\LocaleBundle\Entity\Locale
            api_configuration:
                exposed: true
                dataset: locale.dataset.admin
                manager: locale.manager.admin
