WellCommerce\Bundle\CouponBundle\Entity\CouponTranslation:
    fields:
        name:
            groups:
                - default
                - coupon_translation
        description:
            groups:
                - default
                - coupon_translation
        locale:
            groups:
                - default
                - coupon_translation
        id:
            groups:
                - default
                - coupon_translation
    associations:
        translatable:
            groups:
                - coupon_translation
    callbacks: {  }
