WellCommerce\Bundle\CouponBundle\Entity\Coupon:
    fields:
        id:
            groups:
                - default
                - coupon
        code:
            groups:
                - default
                - coupon
        clientUsageLimit:
            groups:
                - default
                - coupon
        globalUsageLimit:
            groups:
                - default
                - coupon
        modifierType:
            groups:
                - default
                - coupon
        modifierValue:
            groups:
                - default
                - coupon
        validFrom:
            groups:
                - default
                - coupon
        validTo:
            groups:
                - default
                - coupon
        currency:
            groups:
                - default
                - coupon
        createdAt:
            groups:
                - default
                - coupon
        updatedAt:
            groups:
                - default
                - coupon
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        translations:
            groups:
                - coupon
    callbacks: {  }
