well_commerce_producer:
    services:
        producer:
            auto_services:
                factory: WellCommerce\Bundle\ProducerBundle\Factory\ProducerFactory
                repository: WellCommerce\Bundle\ProducerBundle\Repository\ProducerRepository
            orm_configuration:
                mapping: "@WellCommerceProducerBundle/Resources/config/doctrine/Producer.orm.yml"
                entity: WellCommerce\Bundle\ProducerBundle\Entity\Producer
            api_configuration:
                exposed: true
                dataset: producer.dataset.admin
                manager: producer.manager.admin
        producer_route:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommerceProducerBundle/Resources/config/doctrine/ProducerRoute.orm.yml"
                entity: WellCommerce\Bundle\ProducerBundle\Entity\ProducerRoute
        producer_translation:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommerceProducerBundle/Resources/config/doctrine/ProducerTranslation.orm.yml"
                entity: WellCommerce\Bundle\ProducerBundle\Entity\ProducerTranslation
    dynamic_routing:
        name: producer
        entity: WellCommerce\Bundle\ProducerBundle\Entity\ProducerRoute
        generator: WellCommerce\Bundle\ProducerBundle\Routing\ProducerRouteGenerator
        defaults:
            _controller: producer.controller.front:indexAction
            limit: 12
            page: 1
            orderBy: name
            orderDir: asc
            priceFrom: 0
            priceTo: 9999
            view: grid
            producers: ~
            attributes: ~
        requirements:
            limit: "\\d{1,10}"
            page: "\\d{1,10}"
            orderBy: "name|finalPrice"
            orderDir: "asc|desc"
            priceFrom: "\\d{1,10}"
            priceTo: "\\d{1,10}"
            view: "grid|list"
            producers: "[\\d+_]+"
            attributes: "[\\d+_]+"
        pattern: "{page},{limit},{orderBy},{orderDir},{priceFrom},{priceTo},{view},{producers},{attributes}"
