well_commerce_layout:
    services:
        layout_box:
            auto_services:
                factory: WellCommerce\Bundle\LayoutBundle\Factory\LayoutBoxFactory
                repository: WellCommerce\Bundle\LayoutBundle\Repository\LayoutBoxRepository
            orm_configuration:
                mapping: "@WellCommerceLayoutBundle/Resources/config/doctrine/LayoutBox.orm.yml"
                entity: WellCommerce\Bundle\LayoutBundle\Entity\LayoutBox
        layout_box_translation:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommerceLayoutBundle/Resources/config/doctrine/LayoutBoxTranslation.orm.yml"
                entity: WellCommerce\Bundle\LayoutBundle\Entity\LayoutBoxTranslation
