WellCommerce\Bundle\PageBundle\Entity\Page:
    fields:
        id:
            groups:
                - default
                - page
        section:
            groups:
                - default
                - page
        publish:
            groups:
                - default
                - page
        redirectType:
            groups:
                - default
                - page
        redirectUrl:
            groups:
                - default
                - page
        redirectRoute:
            groups:
                - default
                - page
        hierarchy:
            groups:
                - default
                - page
        createdAt:
            groups:
                - default
                - page
        updatedAt:
            groups:
                - default
                - page
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        children:
            groups:
                - page
        clientGroups:
            groups:
                - page
        shops:
            groups:
                - page
        translations:
            groups:
                - page
    callbacks: {  }
