WellCommerce\Bundle\PageBundle\Entity\PageTranslation:
    fields:
        name:
            groups:
                - default
                - page_translation
        content:
            groups:
                - default
                - page_translation
        slug:
            groups:
                - default
                - page_translation
        meta:
            groups:
                - default
                - page_translation
        locale:
            groups:
                - default
                - page_translation
        id:
            groups:
                - default
                - page_translation
    associations:
        route:
            groups:
                - page_translation
        translatable:
            groups:
                - page_translation
    callbacks: {  }
