WellCommerce\Bundle\PageBundle\Entity\PageRoute:
    fields:
        id:
            groups:
                - default
                - page_route
        path:
            groups:
                - default
                - page_route
        locale:
            groups:
                - default
                - page_route
    associations:
        identifier:
            groups:
                - page_route
    callbacks: {  }
