WellCommerce\Bundle\AdminBundle\Entity\AdminMenu:
    fields:
        id:
            groups:
                - default
                - admin_menu
        identifier:
            groups:
                - default
                - admin_menu
        name:
            groups:
                - default
                - admin_menu
        hierarchy:
            groups:
                - default
                - admin_menu
        routeName:
            groups:
                - default
                - admin_menu
        cssClass:
            groups:
                - default
                - admin_menu
    associations:
        children:
            groups:
                - admin_menu
        parent:
            groups:
                - admin_menu
    callbacks: {  }
