WellCommerce\Bundle\AdminBundle\Entity\Role:
    fields:
        id:
            groups:
                - default
                - role
        name:
            groups:
                - default
                - role
        role:
            groups:
                - default
                - role
    associations:
        users:
            groups:
                - role
    callbacks: {  }
