WellCommerce\Bundle\AdminBundle\Entity\User:
    fields:
        id:
            groups:
                - default
                - user
        firstName:
            groups:
                - default
                - user
        lastName:
            groups:
                - default
                - user
        username:
            groups:
                - default
                - user
        password:
            groups: {  }
        email:
            groups:
                - default
                - user
        salt:
            groups: {  }
        enabled:
            groups:
                - default
                - user
        apiKey:
            groups:
                - default
                - user
        createdAt:
            groups:
                - default
                - user
        updatedAt:
            groups:
                - default
                - user
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        roles:
            groups:
                - user
        groups:
            groups:
                - user
    callbacks: {  }
