WellCommerce\Bundle\AdminBundle\Entity\UserGroupPermission:
    fields:
        id:
            groups:
                - default
                - user_group_permission
        name:
            groups:
                - default
                - user_group_permission
        enabled:
            groups:
                - default
                - user_group_permission
        createdAt:
            groups:
                - default
                - user_group_permission
        updatedAt:
            groups:
                - default
                - user_group_permission
    associations:
        group:
            groups:
                - user_group_permission
    callbacks: {  }
