WellCommerce\Bundle\AdminBundle\Entity\UserGroup:
    fields:
        id:
            groups:
                - default
                - user_group
        name:
            groups:
                - default
                - user_group
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        permissions:
            groups:
                - user_group
        users:
            groups:
                - user_group
    callbacks: {  }
