WellCommerce\Bundle\DelivererBundle\Entity\DelivererTranslation:
    type: entity
    table: deliverer_translation
    fields:
        name:
            type: string
            length: 255
            nullable: false
