WellCommerce\Bundle\DistributionBundle\Entity\Package:
    type: entity
    table: distribution_package
    repositoryClass: WellCommerce\Bundle\DistributionBundle\Repository\PackageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fullName:
            type: string
            length: 255
            unique: true
            nullable: false
            column: full_name
        name:
            type: string
            length: 255
            unique: false
            nullable: false
            precision: 0
        vendor:
            type: string
            length: 255
            unique: false
            nullable: false
        localVersion:
            type: string
            length: 255
            unique: false
            nullable: true
            column: local_version
        remoteVersion:
            type: string
            length: 255
            unique: false
            nullable: true
            column: remote_version
