WellCommerce\Bundle\ProductBundle\Entity\ProductTranslation:
    type: entity
    table: product_translation
    embedded:
        meta:
            class: WellCommerce\Bundle\AppBundle\Entity\Meta
    fields:
        name:
            type: string
            length: 255
            nullable: false
        shortDescription:
            type: text
            nullable: true
            column: short_description
        description:
            type: text
            nullable: true
        slug:
            type: string
            length: 255
            unique: true
            nullable: false
    oneToOne:
        route:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\ProductRoute
            cascade:
                - remove
                - persist
            fetch: LAZY
            joinColumns:
                route_id:
                    referencedColumnName: id
                    onDelete: CASCADE
