well_commerce_company:
    services:
        company:
            auto_services:
                factory: WellCommerce\Bundle\CompanyBundle\Factory\CompanyFactory
                repository: WellCommerce\Bundle\CompanyBundle\Repository\CompanyRepository
            orm_configuration:
                mapping: "@WellCommerceCompanyBundle/Resources/config/doctrine/Company.orm.yml"
                entity: WellCommerce\Bundle\CompanyBundle\Entity\Company
            api_configuration:
                exposed: true
                dataset: company.dataset.admin
                manager: company.manager.admin
        company_address:
            orm_configuration:
                mapping: "@WellCommerceCompanyBundle/Resources/config/doctrine/CompanyAddress.orm.yml"
                entity: WellCommerce\Bundle\CompanyBundle\Entity\CompanyAddress
