well_commerce_product:
    services:
        product:
            auto_services:
                factory: WellCommerce\Bundle\ProductBundle\Factory\ProductFactory
                repository: WellCommerce\Bundle\ProductBundle\Repository\ProductRepository
            orm_configuration:
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/Product.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\Product
            api_configuration:
                exposed: true
                dataset: product.dataset.admin
                manager: product.manager.admin
        product_attribute:
            auto_services:
                factory: WellCommerce\Bundle\ProductBundle\Factory\ProductAttributeFactory
                repository: WellCommerce\Bundle\ProductBundle\Repository\ProductAttributeRepository
            orm_configuration:
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/ProductAttribute.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\ProductAttribute
        product_photo:
            auto_services:
                factory: ~
                repository: WellCommerce\Bundle\ProductBundle\Repository\ProductPhotoRepository
            orm_configuration:
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/ProductPhoto.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\ProductPhoto
        product_route:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/ProductRoute.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\ProductRoute
        product_translation:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommerceProductBundle/Resources/config/doctrine/ProductTranslation.orm.yml"
                entity: WellCommerce\Bundle\ProductBundle\Entity\ProductTranslation

    dynamic_routing:
        name: product
        entity: WellCommerce\Bundle\ProductBundle\Entity\ProductRoute
        generator: WellCommerce\Bundle\ProductBundle\Routing\ProductRouteGenerator
        defaults:
            _controller: product.controller.front:indexAction
