WellCommerce\Bundle\DistributionBundle\Entity\Package:
    fields:
        id:
            groups:
                - default
                - package
        fullName:
            groups:
                - default
                - package
        name:
            groups:
                - default
                - package
        vendor:
            groups:
                - default
                - package
        localVersion:
            groups:
                - default
                - package
        remoteVersion:
            groups:
                - default
                - package
        createdAt:
            groups:
                - default
                - package
        updatedAt:
            groups:
                - default
                - package
    associations: {  }
    callbacks: {  }
