WellCommerce\Bundle\AdminBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: WellCommerce\Bundle\AdminBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            length: 64
            unique: false
            nullable: false
            column: first_name
        lastName:
            type: string
            length: 64
            unique: false
            nullable: false
            column: last_name
        username:
            type: string
            length: 25
            unique: true
            nullable: false
        password:
            type: string
            length: 64
            unique: false
            nullable: false
        email:
            type: string
            length: 60
            unique: true
            nullable: false
        salt:
            type: string
            length: 40
            unique: false
            nullable: false
        enabled:
            type: boolean
            length: null
            unique: false
            nullable: false
        apiKey:
            type: string
            length: 40
            unique: true
            nullable: true
    manyToMany:
        roles:
            targetEntity: WellCommerce\Bundle\AdminBundle\Entity\Role
            fetch: LAZY
            inversedBy: users
            joinTable:
                name: user_role
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    -
                        name: role_id
                        referencedColumnName: id
                        onDelete: CASCADE
        groups:
            targetEntity: WellCommerce\Bundle\AdminBundle\Entity\UserGroup
            fetch: LAZY
            inversedBy: users
            joinTable:
                name: user_group_user
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    -
                        name: user_group_id
                        referencedColumnName: id
                        onDelete: CASCADE
