WellCommerce\Bundle\DelivererBundle\Entity\DelivererTranslation:
    fields:
        name:
            groups:
                - default
                - deliverer_translation
        locale:
            groups:
                - default
                - deliverer_translation
        id:
            groups:
                - default
                - deliverer_translation
    associations:
        translatable:
            groups:
                - deliverer_translation
    callbacks: {  }
