well_commerce_shipping:
    services:
        shipping_method:
            auto_services:
                factory: WellCommerce\Bundle\ShippingBundle\Factory\ShippingMethodFactory
                repository: WellCommerce\Bundle\ShippingBundle\Repository\ShippingMethodRepository
            orm_configuration:
                mapping: "@WellCommerceShippingBundle/Resources/config/doctrine/ShippingMethod.orm.yml"
                entity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethod
            api_configuration:
                exposed: true
                dataset: shipping_method.dataset.admin
                manager: shipping_method.manager.admin
        shipping_method_cost:
            auto_services:
                factory: ~
                repository: WellCommerce\Bundle\ShippingBundle\Repository\ShippingMethodCostRepository
            orm_configuration:
                mapping: "@WellCommerceShippingBundle/Resources/config/doctrine/ShippingMethodCost.orm.yml"
                entity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodCost
        shipping_method_translation:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommerceShippingBundle/Resources/config/doctrine/ShippingMethodTranslation.orm.yml"
                entity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodTranslation
