WellCommerce\Bundle\CouponBundle\Entity\CouponTranslation:
    type: entity
    table: coupon_translation
    fields:
        name:
            type: string
            length: 255
            nullable: false
        description:
            type: text
            nullable: true
