well_commerce_news:
    services:
        news:
            auto_services:
                factory: WellCommerce\Bundle\NewsBundle\Factory\NewsFactory
                repository: WellCommerce\Bundle\NewsBundle\Repository\NewsRepository
            orm_configuration:
                mapping: "@WellCommerceNewsBundle/Resources/config/doctrine/News.orm.yml"
                entity: WellCommerce\Bundle\NewsBundle\Entity\News
            api_configuration:
                exposed: true
                dataset: news.dataset.admin
                manager: news.manager.admin
        news_translation:
            orm_configuration:
                mapping: "@WellCommerceNewsBundle/Resources/config/doctrine/NewsTranslation.orm.yml"
                entity: WellCommerce\Bundle\NewsBundle\Entity\NewsTranslation
