well_commerce_product_status:
    services:
        product_status:
            auto_services:
                factory: WellCommerce\Bundle\ProductStatusBundle\Factory\ProductStatusFactory
                repository: WellCommerce\Bundle\ProductStatusBundle\Repository\ProductStatusRepository
            orm_configuration:
                mapping: "@WellCommerceProductStatusBundle/Resources/config/doctrine/ProductStatus.orm.yml"
                entity: WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatus
            api_configuration:
                exposed: true
                dataset: product_status.dataset.admin
                manager: product_status.manager.admin
        product_status_route:
            orm_configuration:
                mapping: "@WellCommerceProductStatusBundle/Resources/config/doctrine/ProductStatusRoute.orm.yml"
                entity: WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatusRoute
        product_status_translation:
            orm_configuration:
                mapping: "@WellCommerceProductStatusBundle/Resources/config/doctrine/ProductStatusTranslation.orm.yml"
                entity: WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatusTranslation
    dynamic_routing:
        name: product_status
        entity: WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatusRoute
        generator: WellCommerce\Bundle\ProductStatusBundle\Routing\ProductStatusRouteGenerator
        defaults:
            _controller: product_status.controller.front:indexAction
            limit: 12
            page: 1
            orderBy: name
            orderDir: asc
            priceFrom: 0
            priceTo: 9999
            view: grid
            producers: ~
            attributes: ~
        requirements:
            limit: "\\d{1,10}"
            page: "\\d{1,10}"
            orderBy: "name|finalPrice"
            orderDir: "asc|desc"
            priceFrom: "\\d{1,10}"
            priceTo: "\\d{1,10}"
            view: "grid|list"
            producers: "[\\d+_]+"
            attributes: "[\\d+_]+"
        pattern: "{page},{limit},{orderBy},{orderDir},{priceFrom},{priceTo},{view},{producers},{attributes}"
