doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\CartBundle\Entity\CartProductInterface: WellCommerce\Bundle\CartBundle\Entity\CartProduct

well_commerce_cart:
    services:
        cart:
            auto_services:
                factory: WellCommerce\Bundle\CartBundle\Factory\CartFactory
                repository: WellCommerce\Bundle\CartBundle\Repository\CartRepository
            orm_configuration:
                mapping: "@WellCommerceCartBundle/Resources/config/doctrine/Cart.orm.yml"
                entity: WellCommerce\Bundle\CartBundle\Entity\Cart
        cart_product:
            auto_services:
                factory: WellCommerce\Bundle\CartBundle\Factory\CartProductFactory
                repository: WellCommerce\Bundle\CartBundle\Repository\CartProductRepository
            orm_configuration:
                mapping: "@WellCommerceCartBundle/Resources/config/doctrine/CartProduct.orm.yml"
                entity: WellCommerce\Bundle\CartBundle\Entity\CartProduct
        cart_totals:
            auto_services:
                factory: WellCommerce\Bundle\CartBundle\Factory\CartTotalsFactory
                repository: ~
            orm_configuration:
                mapping: "@WellCommerceCartBundle/Resources/config/doctrine/CartTotals.orm.yml"
                entity: WellCommerce\Bundle\CartBundle\Entity\CartTotals
