well_commerce_admin:
    services:
        admin_menu:
            auto_services:
                factory: WellCommerce\Bundle\AdminBundle\Factory\AdminMenuFactory
                repository: WellCommerce\Bundle\AdminBundle\Repository\AdminMenuRepository
            orm_configuration:
                mapping: "@WellCommerceAdminBundle/Resources/config/doctrine/AdminMenu.orm.yml"
                entity: WellCommerce\Bundle\AdminBundle\Entity\AdminMenu
        role:
            auto_services:
                factory: WellCommerce\Bundle\AdminBundle\Factory\RoleFactory
                repository: WellCommerce\Bundle\AdminBundle\Repository\RoleRepository
            orm_configuration:
                mapping: "@WellCommerceAdminBundle/Resources/config/doctrine/Role.orm.yml"
                entity: WellCommerce\Bundle\AdminBundle\Entity\Role
        user:
            auto_services:
                factory: WellCommerce\Bundle\AdminBundle\Factory\UserFactory
                repository: WellCommerce\Bundle\AdminBundle\Repository\UserRepository
            orm_configuration:
                mapping: "@WellCommerceAdminBundle/Resources/config/doctrine/User.orm.yml"
                entity: WellCommerce\Bundle\AdminBundle\Entity\User
        user_group:
            auto_services:
                factory: WellCommerce\Bundle\AdminBundle\Factory\UserGroupFactory
                repository: WellCommerce\Bundle\AdminBundle\Repository\UserGroupRepository
            orm_configuration:
                mapping: "@WellCommerceAdminBundle/Resources/config/doctrine/UserGroup.orm.yml"
                entity: WellCommerce\Bundle\AdminBundle\Entity\UserGroup
        user_group_permission:
            orm_configuration:
                mapping: "@WellCommerceAdminBundle/Resources/config/doctrine/UserGroupPermission.orm.yml"
                entity: WellCommerce\Bundle\AdminBundle\Entity\UserGroupPermission
