WellCommerce\Bundle\OrderBundle\Entity\OrderTotal:
    type: embeddable
    fields:
        netAmount:
            type: decimal
            scale: 2
            nullable: false
            precision: 15
            column: net_amount
        grossAmount:
            type: decimal
            scale: 2
            nullable: false
            precision: 15
            column: gross_amount
        taxAmount:
            type: decimal
            scale: 2
            nullable: false
            precision: 15
            column: tax_amount
        taxRate:
            type: decimal
            scale: 2
            nullable: true
            precision: 15
            column: tax_rate
        currency:
            type: string
            length: 16
            nullable: false
            column: currency
