WellCommerce\Bundle\OrderBundle\Entity\OrderTotalDetail:
    type: entity
    table: orders_total
    repositoryClass: WellCommerce\Bundle\OrderBundle\Repository\OrderTotalDetailRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    embedded:
        orderTotal:
            class: WellCommerce\Bundle\OrderBundle\Entity\OrderTotal
            columnPrefix: total_
    fields:
        collector:
            type: string
            nullable: true
        modifierType:
            type: string
            nullable: true
            column: modifier_type
        modifierValue:
            type: decimal
            scale: 2
            nullable: true
            precision: 15
            column: modifier_value
        subtraction:
            type: boolean
            nullable: false
            options:
                default: false
        hierarchy:
            type: integer
            nullable: false
            options:
                default: 0
    manyToOne:
        order:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\Order
            fetch: LAZY
            inversedBy: totals
            joinColumns:
                order_id:
                    referencedColumnName: id
                    onDelete: CASCADE
