WellCommerce\Bundle\AvailabilityBundle\Entity\AvailabilityTranslation:
    fields:
        name:
            groups:
                - default
                - availability_translation
        locale:
            groups:
                - default
                - availability_translation
        id:
            groups:
                - default
                - availability_translation
    associations:
        translatable:
            groups:
                - availability_translation
    callbacks: {  }
