WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatusRoute:
    fields:
        id:
            groups:
                - default
                - product_status_route
        path:
            groups:
                - default
                - product_status_route
        locale:
            groups:
                - default
                - product_status_route
    associations:
        identifier:
            groups:
                - product_status_route
    callbacks: {  }
