WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatus:
    fields:
        id:
            groups:
                - default
                - product_status
        createdAt:
            groups:
                - default
                - product_status
        updatedAt:
            groups:
                - default
                - product_status
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        products:
            groups:
                - product_status
        translations:
            groups:
                - product_status
    callbacks: {  }
