WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatusTranslation:
    fields:
        name:
            groups:
                - default
                - product_status_translation
        cssClass:
            groups:
                - default
                - product_status_translation
        slug:
            groups:
                - default
                - product_status_translation
        meta:
            groups:
                - default
                - product_status_translation
        locale:
            groups:
                - default
                - product_status_translation
        id:
            groups:
                - default
                - product_status_translation
    associations:
        route:
            groups:
                - product_status_translation
        translatable:
            groups:
                - product_status_translation
    callbacks: {  }
