WellCommerce\Bundle\AppBundle\Entity\Dimension:
    fields:
        depth:
            groups:
                - default
                - dimension
        width:
            groups:
                - default
                - dimension
        height:
            groups:
                - default
                - dimension
    associations: {  }
    callbacks: {  }
