WellCommerce\Bundle\AppBundle\Entity\DiscountablePrice:
    fields:
        netAmount:
            groups:
                - default
                - discountable_price
        grossAmount:
            groups:
                - default
                - discountable_price
        taxAmount:
            groups:
                - default
                - discountable_price
        taxRate:
            groups:
                - default
                - discountable_price
        currency:
            groups:
                - default
                - discountable_price
        discountedNetAmount:
            groups:
                - default
                - discountable_price
        discountedGrossAmount:
            groups:
                - default
                - discountable_price
        discountedTaxAmount:
            groups:
                - default
                - discountable_price
        validFrom:
            groups:
                - default
                - discountable_price
        validTo:
            groups:
                - default
                - discountable_price
    associations: {  }
    callbacks: {  }
