WellCommerce\Bundle\AppBundle\Entity\Meta:
    fields:
        title:
            groups:
                - default
                - meta
        keywords:
            groups:
                - default
                - meta
        description:
            groups:
                - default
                - meta
    associations: {  }
    callbacks: {  }
