well_commerce_tax:
    services:
        tax:
            auto_services:
                factory: WellCommerce\Bundle\TaxBundle\Factory\TaxFactory
                repository: WellCommerce\Bundle\TaxBundle\Repository\TaxRepository
            orm_configuration:
                mapping: "@WellCommerceTaxBundle/Resources/config/doctrine/Tax.orm.yml"
                entity: WellCommerce\Bundle\TaxBundle\Entity\Tax
            api_configuration:
                exposed: true
                dataset: tax.dataset.admin
                manager: tax.manager.admin
        tax_translation:
            auto_services:
                factory: ~
                repository: ~
            orm_configuration:
                mapping: "@WellCommerceTaxBundle/Resources/config/doctrine/TaxTranslation.orm.yml"
                entity: WellCommerce\Bundle\TaxBundle\Entity\TaxTranslation
