WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethodTranslation:
    fields:
        name:
            groups:
                - default
                - payment_method_translation
        locale:
            groups:
                - default
                - payment_method_translation
        id:
            groups:
                - default
                - payment_method_translation
    associations:
        translatable:
            groups:
                - payment_method_translation
    callbacks: {  }
