WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethod:
    fields:
        id:
            groups:
                - default
                - payment_method
        processor:
            groups:
                - default
                - payment_method
        enabled:
            groups:
                - default
                - payment_method
        hierarchy:
            groups:
                - default
                - payment_method
        createdAt:
            groups:
                - default
                - payment_method
        updatedAt:
            groups:
                - default
                - payment_method
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        configuration:
            groups:
                - payment_method
        defaultOrderStatus:
            groups:
                - payment_method
        shippingMethods:
            groups:
                - payment_method
        translations:
            groups:
                - payment_method
    callbacks: {  }
