WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethodConfiguration:
    fields:
        id:
            groups:
                - default
                - payment_method_configuration
        name:
            groups:
                - default
                - payment_method_configuration
        value:
            groups:
                - default
                - payment_method_configuration
        createdAt:
            groups:
                - default
                - payment_method_configuration
        updatedAt:
            groups:
                - default
                - payment_method_configuration
    associations:
        paymentMethod:
            groups:
                - payment_method_configuration
    callbacks: {  }
