well_commerce_currency:
    services:
        currency:
            auto_services:
                factory: WellCommerce\Bundle\CurrencyBundle\Factory\CurrencyFactory
                repository: WellCommerce\Bundle\CurrencyBundle\Repository\CurrencyRepository
            orm_configuration:
                mapping: "@WellCommerceCurrencyBundle/Resources/config/doctrine/Currency.orm.yml"
                entity: WellCommerce\Bundle\CurrencyBundle\Entity\Currency
            api_configuration:
                exposed: true
                dataset: currency.dataset.admin
                manager: currency.manager.admin
        currency_rate:
            auto_services:
                factory: WellCommerce\Bundle\CurrencyBundle\Factory\CurrencyRateFactory
                repository: WellCommerce\Bundle\CurrencyBundle\Repository\CurrencyRateRepository
            orm_configuration:
                mapping: "@WellCommerceCurrencyBundle/Resources/config/doctrine/CurrencyRate.orm.yml"
                entity: WellCommerce\Bundle\CurrencyBundle\Entity\CurrencyRate
