WellCommerce\Bundle\UnitBundle\Entity\UnitTranslation:
    type: entity
    table: unit_translation
    fields:
        name:
            type: string
            length: 255
            nullable: false
