WellCommerce\Bundle\LayoutBundle\Entity\LayoutBox:
    fields:
        id:
            groups:
                - default
                - layout_box
        boxType:
            groups:
                - default
                - layout_box
        settings:
            groups:
                - default
                - layout_box
        identifier:
            groups:
                - default
                - layout_box
        createdAt:
            groups:
                - default
                - layout_box
        updatedAt:
            groups:
                - default
                - layout_box
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        translations:
            groups:
                - layout_box
    callbacks: {  }
