WellCommerce\Bundle\LayoutBundle\Entity\LayoutBoxTranslation:
    fields:
        name:
            groups:
                - default
                - layout_box_translation
        content:
            groups:
                - default
                - layout_box_translation
        locale:
            groups:
                - default
                - layout_box_translation
        id:
            groups:
                - default
                - layout_box_translation
    associations:
        translatable:
            groups:
                - layout_box_translation
    callbacks: {  }
