WellCommerce\Bundle\LocaleBundle\Entity\Locale:
    type: entity
    table: locale
    repositoryClass: WellCommerce\Bundle\LocaleBundle\Repository\LocaleRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 12
            unique: true
            nullable: false
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
    manyToOne:
        currency:
            targetEntity: WellCommerce\Bundle\CurrencyBundle\Entity\Currency
            fetch: LAZY
            joinColumns:
                currency_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
            orphanRemoval: false
